    const games = [
        {
        name: "Roblox",
        img: "https://devforum-uploads.s3.dualstack.us-east-2.amazonaws.com/uploads/optimized/4X/f/7/c/f7c9f2a9f31bf5748c52fa1087126828a5333ac8_2_500x500.png",
        description: "A popular platform for creating and playing user-generated games.",
        category: "Platform",
        releaseYear: 2006,
        rating: 4.5,
        },
        {
        name: "Fortnite",
        img: "https://files.oaiusercontent.com/file-KbnNHKGqumSQLmTxpamXSf?se=2024-12-02T03%3A42%3A03Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D604800%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Ddf0c062f-406e-4d26-85ad-e438c3234c52.webp&sig=z0x1tSMcKM9qRi30U7UuZWezVW922jjM8bvPJuQwubM%3D",
        description: "A battle royale game known for its building mechanics.",
        category: "Battle Royale",
        releaseYear: 2017,
        rating: 4.7,
        },
        {
        name: "Genshin Impact",
        img: "https://logos-world.net/wp-content/uploads/2024/01/Genshin-Impact-Logo.jpg",
        description: "An action role-playing game set in a fantasy open-world.",
        category: "Action RPG",
        releaseYear: 2020,
        rating: 4.6,
        },
        {
        name: "Counter-Strike",
        img: "https://static.wikia.nocookie.net/logopedia/images/4/49/Counter-Strike_2_%28Icon%29.png/revision/latest?cb=20230330015359",
        description: "A tactical first-person shooter known for team-based gameplay.",
        category: "FPS",
        releaseYear: 2000,
        rating: 4.8,
        },
        {
        name: "Minecraft",
        img: "https://preview.redd.it/minecraft-logo-v0-ak9w918zi5r81.png?auto=webp&s=614e5180aa1f7068676a06351c8edffc86b3b58a",
        description: "A sandbox game that allows players to build and explore endless worlds.",
        category: "Sandbox",
        releaseYear: 2011,
        rating: 4.9,
        },
        {
        name: "Valorant",
        img: "https://cdn.vectorstock.com/i/1000v/37/87/valorant-game-logo-icon-eps-10-gaming-streamer-vector-33193787.jpg",
        description: "A tactical FPS with unique character abilities.",
        category: "FPS",
        releaseYear: 2020,
        rating: 4.7,
        },
        {
        name: "PlayStation",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Playstation_logo_colour.svg/1280px-Playstation_logo_colour.svg.png",
        description: "A gaming console platform by Sony.",
        category: "Console",
        releaseYear: 1994,
        rating: 4.9,
        },
        {
        name: "GTA Online",
        img: "https://upload.wikimedia.org/wikipedia/commons/2/21/Grand_Theft_Auto_Online_Logo.svg",
        description: "An online multiplayer mode of GTA V.",
        category: "Action-Adventure",
        releaseYear: 2013,
        rating: 4.8,
        },
        {
        name: "War Thunder",
        img: "https://pbs.twimg.com/profile_images/1861735711302410240/j0ppXDRB_400x400.jpg",
        description: "A vehicular combat multiplayer game.",
        category: "Simulator",
        releaseYear: 2012,
        rating: 4.6,
        },
        {
        name: "Steam",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/768px-Steam_icon_logo.svg.png",
        description: "A digital distribution platform for games.",
        category: "Platform",
        releaseYear: 2003,
        rating: 4.8,
        },
        {
        name: "Discord",
        img: "https://logos-world.net/wp-content/uploads/2020/12/Discord-Logo.png",
        description: "A communication platform popular among gamers.",
        category: "Platform",
        releaseYear: 2015,
        rating: 4.7,
        },
        {
        name: "Telegram",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Telegram_2019_Logo.svg/2048px-Telegram_2019_Logo.svg.png",
        description: "A messaging app with gaming communities.",
        category: "Platform",
        releaseYear: 2013,
        rating: 4.6,
        },
        {
        name: "TikTok",
        img: "https://static.vecteezy.com/system/resources/previews/023/986/561/non_2x/tiktok-logo-tiktok-logo-transparent-tiktok-icon-transparent-free-free-png.png",
        description: "A social platform known for short video content.",
        category: "Social",
        releaseYear: 2016,
        rating: 4.5,
        },
        {
        name: "App Store",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/App_Store_%28iOS%29.svg/512px-App_Store_%28iOS%29.svg.png",
        description: "An app distribution platform for iOS devices.",
        category: "Platform",
        releaseYear: 2008,
        rating: 4.8,
        },
        {
        name: "YouTube",
        img: "https://img.freepik.com/premium-vector/youtube-logo-with-red-square_876006-17.jpg",
        description: "A video-sharing platform with a strong gaming community.",
        category: "Social",
        releaseYear: 2005,
        rating: 4.9,
        },
    ];

  export default games;