const games = [
  {
    image:
      "https://i.guim.co.uk/img/media/ecce3f3d2d14d3f78bcc59aebaf119821d603303/67_0_3600_2161/master/3600.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=33bdaa3c150c4b6fd64a1bed0155e8a5",
    name: "Roblox",
    logo: "https://devforum-uploads.s3.dualstack.us-east-2.amazonaws.com/uploads/optimized/4X/f/7/c/f7c9f2a9f31bf5748c52fa1087126828a5333ac8_2_500x500.png",
    description: "A popular platform for creating and playing user-generated games.",
    category: "Platform",
    releaseYear: 2006,
    id: "1",
    rating: 4.5,
    price: 0,
    oldPrice: 0,
    discount: null,
    reviews: 5000,
    watermark: "Roblox Platform",
    status: "Free",
    seller: {
      name: "Roblox Corporation",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    image:
      "https://cdn2.unrealengine.com/social-image-chapter4-s3-3840x2160-d35912cc25ad.jpg",
    name: "Fortnite",
    logo: "https://thumbs.dreamstime.com/b/fortnite-logo-fortnite-logo-white-background-vector-format-available-ai-134361240.jpg",
    description: "A battle royale game known for its building mechanics.",
    category: "Battle Royale",
    releaseYear: 2017,
    id: "2",
    rating: 4.7,
    price: 0,
    oldPrice: 0,
    discount: null,
    reviews: 7000,
    watermark: "Fortnite Game",
    status: "Free",
    seller: {
      name: "Epic Games",
      avatar: "https://cdn-icons-png.flaticon.com/512/147/147144.png",
      verified: true,
    },
  },
  {
    image: "https://i.ytimg.com/vi/AgC2JLuG62U/maxresdefault.jpg",
    name: "Genshin Impact",
    logo: "https://logos-world.net/wp-content/uploads/2024/01/Genshin-Impact-Logo.jpg",
    description: "An action role-playing game set in a fantasy open-world.",
    category: "Action RPG",
    releaseYear: 2020,
    id: "3",
    rating: 4.6,
    price: 0,
    oldPrice: 0,
    discount: null,
    reviews: 6500,
    watermark: "Genshin Open World",
    status: "Free",
    seller: {
      name: "miHoYo",
      avatar: "https://cdn-icons-png.flaticon.com/512/236/236831.png",
      verified: true,
    },
  },
  {
    image:
      "https://lh3.googleusercontent.com/proxy/QTj_E3u2w0iThPqkXmxVFufDvOTFtq6olvjRJHHKNU-xzLjKYYmeGq67bZUe7SNF-msPg4qdjhnQBeE8lDi4vaKN3C833oANLQIwbZ57DeOkOcczkAXk",
    name: "Counter-Strike",
    logo: "https://static.wikia.nocookie.net/logopedia/images/4/49/Counter-Strike_2_%28Icon%29.png/revision/latest?cb=20230330015359",
    description: "A tactical first-person shooter known for team-based gameplay.",
    category: "FPS",
    releaseYear: 2000,
    id: "4",
    rating: 4.8,
    price: 15,
    oldPrice: 20,
    discount: "-25%",
    reviews: 8000,
    watermark: "CS Tactical Shooter",
    status: "Available",
    seller: {
      name: "Valve",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    image:
      "https://store-images.s-microsoft.com/image/apps.53095.13850085746326678.06e2dc5c-7997-46e9-a8e6-0e48b57cb13b.419e3c9d-9dd3-4a28-a9f3-a12350215871",
    name: "Minecraft",
    logo: "https://preview.redd.it/minecraft-logo-v0-ak9w918zi5r81.png?auto=webp&s=614e5180aa1f7068676a06351c8edffc86b3b58a",
    description: "A sandbox game that allows players to build and explore endless worlds.",
    category: "Sandbox",
    releaseYear: 2011,
    id: "5",
    rating: 4.9,
    price: 26.95,
    oldPrice: 30,
    discount: "-10%",
    reviews: 12000,
    watermark: "Minecraft Sandbox",
    status: "Available",
    seller: {
      name: "Mojang Studios",
      avatar: "https://cdn-icons-png.flaticon.com/512/236/236831.png",
      verified: true,
    },
  },
  {
    image:
      "https://img.redbull.com/images/c_limit,w_1500,h_1000/f_auto,q_auto/redbullcom/2020/6/5/ctsejxmdtw9inp8zqqqd/red-bull-campus-clutch-valorant-agents",
    name: "Valorant",
    logo: "https://cdn.vectorstock.com/i/1000v/37/87/valorant-game-logo-icon-eps-10-gaming-streamer-vector-33193787.jpg",
    description: "A tactical FPS with unique character abilities.",
    category: "FPS",
    releaseYear: 2020,
    id: "6",
    rating: 4.7,
    price: 0,
    oldPrice: 0,
    discount: null,
    reviews: 4000,
    watermark: "Valorant FPS",
    status: "Free",
    seller: {
      name: "Riot Games",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "8",
    name: "GTA Online",
    image:
      "https://upload.wikimedia.org/wikipedia/en/a/ab/Grand_Theft_Auto_Online.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/21/Grand_Theft_Auto_Online_Logo.svg",
    description: "An online multiplayer mode of GTA V.",
    category: "Action-Adventure",
    releaseYear: 2013,
    rating: 4.8,
    price: 29.99,
    oldPrice: 49.99,
    discount: "-40%",
    watermark: "GTA Online",
    status: "Available",
    seller: {
      name: "Rockstar Games",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "9",
    name: "War Thunder",
    image: "https://i.ytimg.com/vi/j8YPTKhndTU/hq720.jpg",
    logo: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    description: "A vehicular combat multiplayer game.",
    category: "Simulator",
    releaseYear: 2012,
    rating: 4.6,
    price: 15.99,
    oldPrice: 19.99,
    discount: "-20%",
    watermark: "War Thunder",
    status: "Available",
    seller: {
      name: "Gaijin Entertainment",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "10",
    name: "Steam",
    image:
      "https://www.pcworld.com/wp-content/uploads/2023/11/store_home_share.jpg?quality=50&strip=all",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/768px-Steam_icon_logo.svg.png",
    description: "A digital distribution platform for games.",
    category: "Platform",
    releaseYear: 2003,
    rating: 4.8,
    price: 0,
    watermark: "Steam",
    status: "Free",
    seller: {
      name: "Valve",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "11",
    name: "Discord",
    image:
      "https://sun9-79.userapi.com/s/v1/ig2/lfyQTmdkd3qLGT-E7_HK5hgyGbFihpsL37vPRJKkcumcO4d7az5qus8-AvMTR2J-kEuFN17-Dqt1M_smceNoyI5D.jpg",
    logo: "https://logos-world.net/wp-content/uploads/2020/12/Discord-Logo.png",
    description: "A communication platform popular among gamers.",
    category: "Platform",
    releaseYear: 2015,
    rating: 4.7,
    price: 0,
    watermark: "Discord",
    status: "Free",
    seller: {
      name: "Discord Inc.",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "12",
    name: "Telegram",
    image: "",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Telegram_2019_Logo.svg/2048px-Telegram_2019_Logo.svg.png",
    description: "A messaging app with gaming communities.",
    category: "Platform",
    releaseYear: 2013,
    rating: 4.6,
    price: 0,
    watermark: "Telegram",
    status: "Free",
    seller: {
      name: "Telegram LLC",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "13",
    name: "TikTok",
    image: "",
    logo: "https://static.vecteezy.com/system/resources/previews/023/986/561/non_2x/tiktok-logo-tiktok-logo-transparent-tiktok-icon-transparent-free-free-png.png",
    description: "A social platform known for short video content.",
    category: "Social",
    releaseYear: 2016,
    rating: 4.5,
    price: 0,
    watermark: "TikTok",
    status: "Free",
    seller: {
      name: "ByteDance",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "14",
    name: "App Store",
    image: "",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/App_Store_%28iOS%29.svg/512px-App_Store_%28iOS%29.svg.png",
    description: "An app distribution platform for iOS devices.",
    category: "Platform",
    releaseYear: 2008,
    rating: 4.8,
    price: 0,
    watermark: "App Store",
    status: "Free",
    seller: {
      name: "Apple Inc.",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  {
    id: "15",
    name: "YouTube",
    image: "",
    logo: "https://logo.freepik.com/premium-vector/youtube-logo-with-red-square_876006-17.jpg",
    description: "A video-sharing platform with a strong gaming community.",
    category: "Social",
    releaseYear: 2005,
    rating: 4.9,
    price: 0,
    watermark: "YouTube",
    status: "Free",
    seller: {
      name: "Google",
      avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
      verified: true,
    },
  },
  // Add remaining games similarly...
];

export default games;
